lang: fr
title: Alexandre NIQUET
description: Template pour la création d'un repo type CV
theme: bulma-clean-theme
$primary : '#8849f6'
url: https://github.com/gorinje/craft-the-cv2

force_theme: light
permalink: pretty
lang: fr
theme_color: '#8849f6'
fixed_navbar: top
show_logo: true

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

plugins:
  - jekyll-remote-include

